os: osx
language: swift 
osx_image: xcode10
before_install:
- brew install git-lfs

before_script:
- git lfs install
- git lfs pull
- xcodebuild clean

script:
- set -o pipefail && xcodebuild -workspace PSS.xcworkspace -scheme PSS -destination platform\=iOS\ Simulator,OS\=12.0,name\=iPhone\ 8 -only-testing:Simulator_UITests build test | xcpretty